"""Markdown → PDF converter for downloadable reports.

Pure-Python pipeline (markdown → HTML → PDF via fpdf2). No system dependencies
required (no cairo, no wkhtmltopdf), so it works on Streamlit Cloud, Render,
Railway, and local dev alike.
"""
from __future__ import annotations

from io import BytesIO

import markdown
from fpdf import FPDF


def markdown_to_pdf(md_text: str, *, title: str | None = None) -> bytes:
    """Render a Markdown string to PDF bytes.

    Returns raw bytes ready to feed Streamlit's `download_button(data=...)`.
    """
    html_body = markdown.markdown(
        md_text,
        extensions=["extra", "sane_lists", "nl2br"],
    )

    pdf = FPDF(format="A4")
    pdf.set_margins(left=20, top=20, right=20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    # Use the built-in Unicode-capable font alias (uses core fonts under the hood;
    # for full Unicode the user can bundle a TTF later).
    pdf.set_font("Helvetica", size=11)

    # fpdf2 ships a basic HTML renderer that handles h1–h6, p, ul/ol/li,
    # strong/em, br, hr, and a, which covers everything `markdown` outputs.
    pdf.write_html(html_body)

    # Footer
    pdf.ln(6)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, "Generated by Multi-Agent Research Analyst", align="C")

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
