"""Markdown → PDF converter for downloadable reports.

Pure-Python pipeline (markdown → HTML → PDF via xhtml2pdf), so it works on
Windows without GTK/wkhtmltopdf system dependencies.
"""
from __future__ import annotations

from io import BytesIO

import markdown
from xhtml2pdf import pisa

# Light, print-friendly stylesheet. Inline so the PDF is self-contained.
_CSS = """
@page { size: A4; margin: 2cm; }
body { font-family: Helvetica, Arial, sans-serif; font-size: 11pt;
       line-height: 1.45; color: #222; }
h1 { font-size: 22pt; color: #1a1a1a; border-bottom: 2px solid #444;
     padding-bottom: 6px; margin-top: 0; }
h2 { font-size: 15pt; color: #2c3e50; margin-top: 22px; }
h3 { font-size: 12pt; color: #34495e; }
p  { margin: 8px 0; text-align: justify; }
ul, ol { margin: 6px 0 10px 18px; }
li { margin: 3px 0; }
strong { color: #111; }
em { color: #555; }
code { background: #f4f4f4; padding: 1px 4px; border-radius: 3px;
       font-family: 'Courier New', monospace; font-size: 10pt; }
blockquote { border-left: 3px solid #999; padding-left: 10px; color: #555;
             margin: 10px 0; }
hr { border: none; border-top: 1px solid #ccc; margin: 16px 0; }
.footer { font-size: 8pt; color: #888; text-align: center; margin-top: 24px; }
"""


def markdown_to_pdf(md_text: str, *, title: str | None = None) -> bytes:
    """Render a Markdown string to PDF bytes.

    Returns raw bytes ready to feed Streamlit's `download_button(data=...)`.
    """
    html_body = markdown.markdown(
        md_text,
        extensions=["extra", "sane_lists", "nl2br"],
    )

    page_title = (title or "Research Report").replace("<", "&lt;").replace(">", "&gt;")
    full_html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{page_title}</title>
  <style>{_CSS}</style>
</head>
<body>
  {html_body}
  <div class="footer">Generated by Multi-Agent Research Analyst</div>
</body>
</html>"""

    buf = BytesIO()
    result = pisa.CreatePDF(src=full_html, dest=buf, encoding="utf-8")
    if result.err:
        raise RuntimeError(f"xhtml2pdf failed with {result.err} errors")
    return buf.getvalue()
